### ISSUE TITLE
Deployment template validation failed on Azure Cloud Shell

### ISSUE THREAD

**Issue by trishaulr** [MicrosoftDocs/mslearn-distribute-load-with-traffic-manager#9] opened 2020-04-28 16:01 UTC
Deploying the template as part of the traffic manager lab (https://docs.microsoft.com/en-gb/learn/modules/distribute-load-with-traffic-manager/3-exercise-priority-routing) with the following command:

az deployment group create \
    --resource-group learn-8c224e6d-afa8-4b91-8e7e-c76ecf1f4545 \
    --template-uri  https://raw.githubusercontent.com/MicrosoftDocs/mslearn-distribute-load-with-traffic-manager/master/azuredeploy.json \
    --parameters password="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32)"

results in the following error:

{'additionalProperties': {}, 'code': 'InvalidTemplate', 'message': "Deployment template validation failed: 'The template variable 'deploymentUrl' is not valid: The language expression property 'templateLink'doesn't exist, available properties are 'template, templateHash, parameters, mode, provisioningState'..Please see https://aka.ms/arm-template-expressions for usage details.'.", 'target': None, 'details': None, 'additionalInfo': [{'additionalProperties': {}, 'type': 'TemplateViolation', 'info': {'lineNumber': 14, 'linePosition': 69, 'path': 'properties.template.variables.deploymentUrl'}}]}

**Comment by pauldj54** [comment] 2020-05-01 13:29
Hi, 
I can confirm the error described by @trishaulr 
I think the problem is, the linked template is not accessible from the sandbox.
Best, 
Paul

**Comment by turbotmy** [comment] 2020-05-26 03:30
i have the same problem, think the deployment uri validation is not correctly expressed on the deploymentUrl

**Comment by jboeshart** [comment] 2020-05-28 14:04
Fixed in #12

**Closed by jboeshart** 2020-05-28 14:04 UTC
